name: PHP Code Beautifier Check

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.yml'
  pull_request:
  workflow_dispatch:

jobs:
  phpcbf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Adjust this to your PHP version
          extensions: uopz

      - name: Install PHP_CodeSniffer
        run: composer install --prefer-dist --no-progress --ignore-platform-reqs

      - name: Run phpcbf
        run: |
          ./vendor/bin/phpcbf src templates assets -q

      - name: Check for changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "phpcbf made changes to the code. Please fix these issues before committing."
            git --no-pager diff
            exit 1
          else
            echo "No changes detected. Code is properly formatted."
          fi
