name: PHP Code Beautifier Check

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.yml'
  pull_request:
  workflow_dispatch:

jobs:
  phpcbf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Adjust this to your PHP version
          extensions: uopz

      - name: Install PHP_CodeSniffer
        run: composer install --prefer-dist --no-progress --ignore-platform-reqs

      - name: Run phpcbf
        run: |
          ./vendor/bin/phpcbf -q --parallel=1 src templates assets 2>&1 | tee phpcbf.output.txt

      - name: Check for changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "phpcbf made changes to the code. Please fix these issues before committing."
            git --no-pager diff
            exit 1
          else
            echo "No changes detected. Code is properly formatted."
          fi

  report-phpcbf:
    needs: phpcbf
    if: failure()
    runs-on: ubuntu-latest
    steps:

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: PHP Code Beautifier and Fixer found the following fixable issues

      - name: Read phpcbf output file
        id: getversion
        run: echo "content=$(cat phpcbf.output.txt)" >> $GITHUB_OUTPUT

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            PHP Code Beautifier and Fixer found the following fixable issues:
            ${{ steps.getcontent.outputs.content }}
          edit-mode: replace
