name: Deploy to WordPress.org

on:
  release:
    types: [published]

jobs:
  publish:
    name: New Release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:

    - uses: actions/checkout@v7

    - uses: ./.github/actions/build-plugin

    - name: Check i18n coverage before release
      uses: alexkiro/i18n-coverage@v1.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        translations-path: 'languages/*.po'
        ignore-languages: 'en'
        min-coverage: 100
        
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        dry-run: false
        generate-zip: true
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        BUILD_DIR: build/commonsbooking
        SLUG: commonsbooking # optional, remove if GitHub repo name matches SVN slug, including capitalization

    - name: Upload release asset
      uses: softprops/action-gh-release@v3
      with:
        files: ${{ steps.deploy.outputs.zip-path }}