name: Run automated tests
on:
  push:
    branches:
      - 'master'
      - 'release/**'
    paths-ignore:
      - '**.md'
      - '**.txt'
  pull_request:
    branches:
      - 'master'

jobs:
  phpunit-php74:
      name: PHP Unit Tests (PHP 7.4)
      uses: ./.github/workflows/phpunit.yml 
      with:
        php-version: '7.4'
        codecov-upload: true
      secrets:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  phpunit-php82:
      name: PHP Unit Tests (PHP 8.2)
      uses: ./.github/workflows/phpunit.yml 
      with:
        php-version: '8.2'
        codecov-upload: false
        
  e2e-php74:
      name: E2E Tests (PHP 7.4)
      uses: ./.github/workflows/e2e.yml 
      with:
        php-version: '7.4'

  e2e-php82:
      name: E2E Tests (PHP 8.2)
      uses: ./.github/workflows/e2e.yml 
      with:
        php-version: '8.2'
