<?php
/**
 * Validates that data generated by generate_cb_testdata.py --format php
 * produces posts that CommonsBooking's model layer can correctly resolve.
 *
 * This test loads a small fixture, then uses the plugin's own model classes
 * to verify that bookings can find their item, location, and that timeframes
 * link items to locations correctly.
 *
 * Place this file at: tests/php/Fixture/GeneratedFixtureValidationTest.php
 *
 * Generate the fixture first:
 *   python generate_cb_testdata.py --format php --seed 42 \
 *     --bookings 5 --locations 2 --items 2 \
 *     -o tests/benchmark/fixtures/benchmark-data.php
 *
 * Run:
 *   php ~/phpunit.phar --bootstrap tests/php/bootstrap.php \
 *     tests/php/Fixture/GeneratedFixtureValidationTest.php
 */

namespace CommonsBooking\Tests\Fixture;

use CommonsBooking\Model\Booking;
use CommonsBooking\Model\Timeframe;
use CommonsBooking\Wordpress\CustomPostType\Timeframe as TimeframeCPT;
use WP_UnitTestCase;

class GeneratedFixtureValidationTest extends WP_UnitTestCase {

	private static bool $fixtureLoaded = false;

	public static function setUpBeforeClass(): void {
		parent::setUpBeforeClass();

		$fixturePath = __DIR__ . '/../benchmark/fixtures/benchmark-data.php';
		if ( ! file_exists( $fixturePath ) ) {
			self::markTestSkipped(
				'Fixture file not found. Generate it first with: ' .
				'python generate_cb_testdata.py --format php --seed 42 ' .
				'--bookings 5 --locations 2 --items 2 ' .
				'-o tests/benchmark/fixtures/benchmark-data.php'
			);
		}

		require_once $fixturePath;
		cb_benchmark_load_fixtures();
		self::$fixtureLoaded = true;
	}

	public static function tearDownAfterClass(): void {
		if ( self::$fixtureLoaded && function_exists( 'cb_benchmark_cleanup_fixtures' ) ) {
			cb_benchmark_cleanup_fixtures();
		}
		parent::tearDownAfterClass();
	}

	/**
	 * Verify that locations were created with the correct post type.
	 */
	public function testLocationsExist(): void {
		$locations = get_posts( [
			'post_type'   => 'cb_location',
			'post_status' => 'publish',
			'numberposts' => -1,
			'fields'      => 'ids',
		] );

		$this->assertNotEmpty( $locations, 'No cb_location posts found in fixture' );

		foreach ( $locations as $locationId ) {
			$post = get_post( $locationId );
			$this->assertEquals( 'cb_location', $post->post_type );
			$this->assertEquals( 'publish', $post->post_status );

			// Locations should have geo coordinates
			$lat = get_post_meta( $locationId, 'geo_latitude', true );
			$lng = get_post_meta( $locationId, 'geo_longitude', true );
			$this->assertNotEmpty( $lat, "Location $locationId missing geo_latitude" );
			$this->assertNotEmpty( $lng, "Location $locationId missing geo_longitude" );
		}
	}

	/**
	 * Verify that items were created with the correct post type.
	 */
	public function testItemsExist(): void {
		$items = get_posts( [
			'post_type'   => 'cb_item',
			'post_status' => 'publish',
			'numberposts' => -1,
			'fields'      => 'ids',
		] );

		$this->assertNotEmpty( $items, 'No cb_item posts found in fixture' );

		foreach ( $items as $itemId ) {
			$post = get_post( $itemId );
			$this->assertEquals( 'cb_item', $post->post_type );
		}
	}

	/**
	 * Verify timeframes have correct type and link to valid items + locations.
	 */
	public function testTimeframesLinkToItemsAndLocations(): void {
		$timeframes = get_posts( [
			'post_type'   => 'cb_timeframe',
			'post_status' => 'publish',
			'numberposts' => -1,
			'fields'      => 'ids',
		] );

		$this->assertNotEmpty( $timeframes, 'No cb_timeframe posts found in fixture' );

		foreach ( $timeframes as $tfId ) {
			$type = get_post_meta( $tfId, 'type', true );
			$this->assertEquals(
				(string) TimeframeCPT::BOOKABLE_ID,
				$type,
				"Timeframe $tfId should have type=" . TimeframeCPT::BOOKABLE_ID . " (BOOKABLE_ID), got '$type'"
			);

			// Check item-id points to a real cb_item
			$itemId = get_post_meta( $tfId, Timeframe::META_ITEM_ID, true );
			$this->assertNotEmpty( $itemId, "Timeframe $tfId missing item-id" );
			$itemPost = get_post( (int) $itemId );
			$this->assertNotNull( $itemPost, "Timeframe $tfId item-id=$itemId does not exist" );
			$this->assertEquals( 'cb_item', $itemPost->post_type, "Timeframe $tfId item-id=$itemId is not a cb_item" );

			// Check location-id points to a real cb_location
			$locationId = get_post_meta( $tfId, Timeframe::META_LOCATION_ID, true );
			$this->assertNotEmpty( $locationId, "Timeframe $tfId missing location-id" );
			$locationPost = get_post( (int) $locationId );
			$this->assertNotNull( $locationPost, "Timeframe $tfId location-id=$locationId does not exist" );
			$this->assertEquals( 'cb_location', $locationPost->post_type, "Timeframe $tfId location-id=$locationId is not a cb_location" );

			// Check date meta
			$repStart = get_post_meta( $tfId, Timeframe::REPETITION_START, true );
			$repEnd   = get_post_meta( $tfId, Timeframe::REPETITION_END, true );
			$this->assertNotEmpty( $repStart, "Timeframe $tfId missing repetition-start" );
			$this->assertNotEmpty( $repEnd, "Timeframe $tfId missing repetition-end" );
			$this->assertGreaterThan( 0, (int) $repStart );
			$this->assertGreaterThanOrEqual( (int) $repStart, (int) $repEnd );

			// Check selection types are set
			$itemSelect     = get_post_meta( $tfId, Timeframe::META_ITEM_SELECTION_TYPE, true );
			$locationSelect = get_post_meta( $tfId, Timeframe::META_LOCATION_SELECTION_TYPE, true );
			$this->assertNotEmpty( $itemSelect, "Timeframe $tfId missing item-select" );
			$this->assertNotEmpty( $locationSelect, "Timeframe $tfId missing location-select" );
		}
	}

	/**
	 * Verify bookings have type=6 (BOOKING_ID), correct post_status,
	 * and link to valid items + locations.
	 */
	public function testBookingsHaveCorrectTypeAndRelations(): void {
		$bookings = get_posts( [
			'post_type'   => 'cb_booking',
			'post_status' => [ 'confirmed', 'unconfirmed', 'canceled' ],
			'numberposts' => -1,
			'fields'      => 'ids',
		] );

		$this->assertNotEmpty( $bookings, 'No cb_booking posts found in fixture' );

		foreach ( $bookings as $bookingId ) {
			$post = get_post( $bookingId );

			// type meta must be 6 (BOOKING_ID), not 2
			$type = get_post_meta( $bookingId, 'type', true );
			$this->assertEquals(
				(string) TimeframeCPT::BOOKING_ID,
				$type,
				"Booking $bookingId should have type=" . TimeframeCPT::BOOKING_ID . " (BOOKING_ID), got '$type'"
			);

			// post_status should be one of the booking statuses
			$this->assertContains(
				$post->post_status,
				[ 'confirmed', 'unconfirmed', 'canceled' ],
				"Booking $bookingId has unexpected post_status '{$post->post_status}'"
			);

			// Check item-id points to a real cb_item
			$itemId = get_post_meta( $bookingId, Timeframe::META_ITEM_ID, true );
			$this->assertNotEmpty( $itemId, "Booking $bookingId missing item-id" );
			$itemPost = get_post( (int) $itemId );
			$this->assertNotNull( $itemPost, "Booking $bookingId item-id=$itemId does not exist" );
			$this->assertEquals( 'cb_item', $itemPost->post_type );

			// Check location-id points to a real cb_location
			$locationId = get_post_meta( $bookingId, Timeframe::META_LOCATION_ID, true );
			$this->assertNotEmpty( $locationId, "Booking $bookingId missing location-id" );
			$locationPost = get_post( (int) $locationId );
			$this->assertNotNull( $locationPost, "Booking $bookingId location-id=$locationId does not exist" );
			$this->assertEquals( 'cb_location', $locationPost->post_type );

			// Check date meta
			$repStart = get_post_meta( $bookingId, Timeframe::REPETITION_START, true );
			$repEnd   = get_post_meta( $bookingId, Timeframe::REPETITION_END, true );
			$this->assertNotEmpty( $repStart, "Booking $bookingId missing repetition-start" );
			$this->assertNotEmpty( $repEnd, "Booking $bookingId missing repetition-end" );
			$this->assertGreaterThan( 0, (int) $repStart );
			$this->assertGreaterThanOrEqual( (int) $repStart, (int) $repEnd );
		}
	}

	/**
	 * Verify that the Booking model can resolve its item and location
	 * via the plugin's own model layer.
	 */
	public function testBookingModelResolvesRelations(): void {
		$bookings = get_posts( [
			'post_type'   => 'cb_booking',
			'post_status' => 'confirmed',
			'numberposts' => 1,
		] );

		$this->assertNotEmpty( $bookings, 'No confirmed bookings found' );

		$bookingModel = new Booking( $bookings[0] );

		// getItem() and getLocation() should return model objects
		$item = $bookingModel->getItem();
		$this->assertNotNull( $item, 'Booking::getItem() returned null' );
		$this->assertEquals( 'cb_item', get_post_type( $item->ID ) );

		$location = $bookingModel->getLocation();
		$this->assertNotNull( $location, 'Booking::getLocation() returned null' );
		$this->assertEquals( 'cb_location', get_post_type( $location->ID ) );
	}

	/**
	 * Verify that a Timeframe model can be constructed and returns valid data.
	 */
	public function testTimeframeModelResolvesRelations(): void {
		$timeframes = get_posts( [
			'post_type'   => 'cb_timeframe',
			'post_status' => 'publish',
			'numberposts' => 1,
		] );

		$this->assertNotEmpty( $timeframes, 'No timeframes found' );

		$tfModel = new Timeframe( $timeframes[0] );

		$item = $tfModel->getItem();
		$this->assertNotNull( $item, 'Timeframe::getItem() returned null' );
		$this->assertEquals( 'cb_item', get_post_type( $item->ID ) );

		$location = $tfModel->getLocation();
		$this->assertNotNull( $location, 'Timeframe::getLocation() returned null' );
		$this->assertEquals( 'cb_location', get_post_type( $location->ID ) );

		// Check that date accessors work
		$startDate = $tfModel->getStartDate();
		$this->assertNotEmpty( $startDate, 'Timeframe::getStartDate() returned empty' );
	}

	/**
	 * Verify the overall count matches what the generator was told to create.
	 * Adjust these numbers if you regenerate with different params.
	 */
	public function testFixtureCounts(): void {
		$locations  = get_posts( [ 'post_type' => 'cb_location', 'post_status' => 'publish', 'numberposts' => -1 ] );
		$items      = get_posts( [ 'post_type' => 'cb_item', 'post_status' => 'publish', 'numberposts' => -1 ] );
		$timeframes = get_posts( [ 'post_type' => 'cb_timeframe', 'post_status' => 'publish', 'numberposts' => -1 ] );
		$bookings   = get_posts( [ 'post_type' => 'cb_booking', 'post_status' => [ 'confirmed', 'unconfirmed', 'canceled' ], 'numberposts' => -1 ] );

		// With --locations 2 --items 2 --bookings 5:
		// 2 locations, 2 items, 4 timeframes (2×2), 5 bookings
		$this->assertGreaterThanOrEqual( 1, count( $locations ), 'Expected at least 1 location' );
		$this->assertGreaterThanOrEqual( 1, count( $items ), 'Expected at least 1 item' );
		$this->assertGreaterThanOrEqual( 1, count( $timeframes ), 'Expected at least 1 timeframe' );
		$this->assertGreaterThanOrEqual( 1, count( $bookings ), 'Expected at least 1 booking' );

		// Timeframes should equal items × locations
		$this->assertEquals(
			count( $items ) * count( $locations ),
			count( $timeframes ),
			'Expected one timeframe per item×location pair'
		);
	}
}
